apiVersion: v1
kind: PersistentVolume
metadata:
  name: minecraftum-pv
  labels:
    type: local
spec:
  storageClassName: manual
  capacity:
    storage: 10Gi
  accessModes:
    - ReadWriteOnce
  hostPath:
    path: "/opt/minecraftum/data"
---

apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: minecraftum-pvc
spec:
  storageClassName: manual
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 10Gi
---

apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: minecraftum-dep
  name: minecraftum-dep
spec:
  replicas: 1
  selector:
    matchLabels:
      app: minecraftum-dep
  template:
    metadata:
      labels:
        app: minecraftum-dep
    spec:
      containers:
      - name: minecraftum
        image: localhost:32000/minecraftum:1.0.0
        imagePullPolicy: Always
        ports:
        - containerPort: 25565
        volumeMounts:
          - name: data
            mountPath: "/opt/minecraftum/data"
      volumes:
      - name: data
        persistentVolumeClaim:
          claimName: minecraftum-pvc
---
apiVersion: v1
kind: Service
metadata:
  name: minecraftum
spec:
  type: LoadBalancer
  selector:
    app: minecraftum
  ports:
    - port: 19151
      targetPort: 25565
      protocol: UDP
---
