FROM docker.io/library/eclipse-temurin:21-jre-alpine

#----- Setup minecraft serv -----
WORKDIR /app

COPY requirements.txt start_server.py ./

RUN apk add --no-cache python3 py3-requests
RUN mkdir data
WORKDIR /app/data

EXPOSE 25565

#----- Run -----
CMD ["uv", "run", "/app/start_server.py"]
