name: GitHub CI/CD
run-name: ${{ github.actor }} pushing, testing and deploying a new version of Minecraftum
on:
  push:
    branches:
      - "main"
jobs:
  Check_Build_Minecraftum_Container_Image:
    runs-on: self-hosted
    outputs:
      is-build-required: ${{ steps.step_check_folder.outputs.build_req }}
    steps:
      - name: Check out repository code
        uses: actions/checkout@v3
        with:
          fetch-depth: 2

  Build_Minecraftum_Container_Image:
    needs: Check_Build_Minecraftum_Container_Image
    runs-on: self-hosted
    # if: needs.Check_Build_Minecraftum_Container_Image.outputs.is-build-required == 'true'
    steps:
      - name: Podman Cleanup current containers
        run: podman rmi --all -f
      - name: Podman Building Minecraftum Image Back
        run: podman build -t localhost:32000/minecraftum ./minecraftum/

  Test_Minecraftum_Container_Image:
    runs-on: self-hosted
    needs: Build_Minecraftum_Container_Image
    steps:
      - name: Podman Testing Minecraftum Image Front
        run: podman run --entrypoint echo "test inside a container" localhost:32000/minecraftum:latest 

  Push_Minecraftum_Container_Image:
    runs-on: self-hosted
    needs: Test_Minecraftum_Container_Image
    steps:
      - name: Podman push Prod Minecraftum Image Back
        run: podman push --tls-verify=false  localhost:32000/minecraftum:latest

  Cleanup_Minecraftum:
    runs-on: self-hosted
    needs: Push_Minecraftum_Container_Image
    steps:
      - name: Podman cleanup images
        run: podman image prune -f || true
      - name: Podman cleanup containers
        run: podman container prune -f || true
