name: GitHub CI/CD
run-name: ${{ github.actor }} pushing, testing and deploying a new version of Minecraftum
on:
  push:
    branches:
      - "main"
jobs:
  Check_Build_Minecraftum_Container_Image:
    runs-on: self-hosted
    outputs:
      is-build-required: ${{ steps.step_check_folder.outputs.build_req }}
    steps:
      - name: Check out repository code
        uses: actions/checkout@v3
        with:
          fetch-depth: 2

  Build_Minecraftum_Container_Image:
    needs: Check_Build_Minecraftum_Container_Image
    runs-on: self-hosted
    # if: needs.Check_Build_Minecraftum_Container_Image.outputs.is-build-required == 'true'
    steps:
      - name: Podman Cleanup current containers
        run: podman rmi docker.io/k4rim/minecraftum:alp -f
      - name: Podman Building Minecraftum Image
        run: podman build -t docker.io/k4rim/minecraftum:alp -f ./minecraftum/Dockerfile ./minecraftum/
  
  Push_Minecraftum_Container_Image:
    runs-on: self-hosted
    needs: Build_Minecraftum_Container_Image
    steps:
      - name: Podman login Prod Minecraftum Image Dockerhub
        env:
          TOKEN: ${{ secrets.TOKEN }}
        run: podman login -u k4rim -p $TOKEN docker.io/k4rim

      - name: Podman push Prod Minecraftum Image
        run: podman push --tls-verify=false  docker.io/k4rim/minecraftum:alp

  Cleanup_Minecraftum:
    runs-on: self-hosted
    needs: Push_Minecraftum_Container_Image
    steps:
      - name: Podman cleanup images
        run: podman image prune -f || true
      - name: Podman cleanup containers
        run: podman container prune -f || true
